registry: "fritzduchardt"

oneshotUi:
  image: oneshot-ui
  tag: main
  replicas: 1
  service:
    port: 3000
    targetPort: 3000
  env:
    - name: PORT
      value: 3000
  ingress:
    className: "nginx"
    host: oneshot.duchardt.net
    tlsSecretName: oneshot-certificate
    clusterIssuer: http01
  basicAuth:
    authFile: ""
    secretName: oneshot-ui-basic-auth

oneshot:
  image: oneshot
  tag: main
  replicas: 1
  service:
    port: 8080
    targetPort: 8080
  config:
    oneshotEnvFile: /app/.oneshot/.env
  env:
    - name: OS_CONFIG_ENV_FILE
      value: /app/.oneshot/.env
    - name: OS_CONFIG_PATTERN_DIR
      value: /app/.oneshot/patterns
    - name: OS_MARKDOWN_BASE_DIR
      value: /sync
    - name: OS_MARKDOWN_VAULT_DIR_1
      value: FritzSync/private
    - name: OS_MARKDOWN_VAULT_DIR_2
      value: BubaFritzShare/private
    - name: OS_PATTERN_TEMPLATE_DIR
      value: /sync/FritzSync/patterns
    - name: LOG_LEVEL
      value: info
    - name: MCP_URL
      value: http://oneshot-mcp:8081
    - name: WEAVIATE_HOST
      value: weaviate.weaviate
    - name: WEAVIATE_PORT
      value: 80
    - name: WEAVIATE_GRPC_PORT
      value: 50051
  nodeSelector: friclu-1
  host:
    syncDir: "/volumes/syncthing"

oneshotMcp:
  image: oneshot-mcp
  tag: main
  replicas: 1
  service:
    port: 9000
    targetPort: 9000
  env:
    - name: OS_CONFIG_PATTERN_DIR
      value: /app/src/.oneshot/patterns
    - name: OS_MARKDOWN_BASE_DIR
      value: /sync
    - name: OS_MARKDOWN_VAULT_DIR_1
      value: FritzSync/private
    - name: OS_MARKDOWN_VAULT_DIR_2
      value: BubaFritzShare/private
    - name: LOG_LEVEL
      value: info
  nodeSelector: {}
