apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oneshot
  labels:
    app.kubernetes.io/name: oneshot
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.ingress.basicAuthSecret }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Ensure streaming responses work by disabling buffering, using HTTP/1.1, and increasing timeouts
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-cache: "off"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /backend/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: oneshot
            port:
              name: http
      - path: /image/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: oneshot
            port:
              name: http
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: oneshot-ui
            port:
              name: http