apiVersion: v1
kind: Service
metadata:
  name: oneshot-nginx
  labels:
    app.kubernetes.io/name: oneshot
    app.kubernetes.io/component: nginx
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: oneshot
    app.kubernetes.io/component: nginx
  ports:
    - name: http
      port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.targetPort }}