apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: markdown-dir
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: markdown-dir
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pattern-dir
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: pattern-dir
