apiVersion: v1
kind: PersistentVolume
metadata:
  name: sync-dir
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: {{ .Values.oneshot.host.markdownDir }}
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem